import { Store, City, Offer } from './types';

export const stores: Store[] = [
  {
    id: '1',
    name: 'Lidl',
    slug: 'lidl',
    brandColor: '#0050AA',
    websiteUrl: 'https://www.lidl.de',
  },
  {
    id: '2',
    name: 'Aldi Süd',
    slug: 'aldi-sued',
    brandColor: '#00005F',
    websiteUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '3',
    name: 'Penny',
    slug: 'penny',
    brandColor: '#CD1719',
    websiteUrl: 'https://www.penny.de',
  },
  {
    id: '4',
    name: 'Kaufland',
    slug: 'kaufland',
    brandColor: '#E10915',
    websiteUrl: 'https://www.kaufland.de',
  },
  {
    id: '5',
    name: 'Netto',
    slug: 'netto',
    brandColor: '#FFE600',
    websiteUrl: 'https://www.netto-online.de',
  },
  {
    id: '6',
    name: 'Rewe',
    slug: 'rewe',
    brandColor: '#CC071E',
    websiteUrl: 'https://www.rewe.de',
  },
];

export const cities: City[] = [
  { id: "1", name: "Hamburg", slug: "hamburg", state: "Hamburg" },
  { id: "2", name: "Berlin", slug: "berlin", state: "Berlin" },
  { id: "3", name: "Munich", slug: "munich", state: "Bavaria" },
  { id: "4", name: "Cologne", slug: "cologne", state: "North Rhine-Westphalia" },
  { id: "5", name: "Frankfurt", slug: "frankfurt", state: "Hesse" },
  { id: "6", name: "Stuttgart", slug: "stuttgart", state: "Baden-Württemberg" },
  { id: "7", name: "Düsseldorf", slug: "duesseldorf", state: "North Rhine-Westphalia" },
  { id: "8", name: "Leipzig", slug: "leipzig", state: "Saxony" },
  { id: "9", name: "Dresden", slug: "dresden", state: "Saxony" },
  { id: "10", name: "Hannover", slug: "hannover", state: "Lower Saxony" },
  { id: "11", name: "Nuremberg", slug: "nuremberg", state: "Bavaria" },
  { id: "12", name: "Bremen", slug: "bremen", state: "Bremen" },
  { id: "13", name: "Regensburg", slug: "regensburg", state: "Bavaria" },
  { id: "14", name: "Heidelberg", slug: "heidelberg", state: "Baden-Württemberg" },
  { id: "15", name: "Freiburg", slug: "freiburg", state: "Baden-Württemberg" },
  { id: "16", name: "Aachen", slug: "aachen", state: "North Rhine-Westphalia" },
  { id: "17", name: "Göttingen", slug: "goettingen", state: "Lower Saxony" },
  { id: "18", name: "Mannheim", slug: "mannheim", state: "Baden-Württemberg" },
  { id: "19", name: "Karlsruhe", slug: "karlsruhe", state: "Baden-Württemberg" },
  { id: "20", name: "Bonn", slug: "bonn", state: "North Rhine-Westphalia" },
  { id: "21", name: "Münster", slug: "muenster", state: "North Rhine-Westphalia" },
  { id: "22", name: "Augsburg", slug: "augsburg", state: "Bavaria" },
  { id: "23", name: "Würzburg", slug: "wuerzburg", state: "Bavaria" },
  { id: "24", name: "Kiel", slug: "kiel", state: "Schleswig-Holstein" },
  { id: "25", name: "Dortmund", slug: "dortmund", state: "North Rhine-Westphalia" },
];

export const offers: Offer[] = [
  // Avocado
  {
    id: '1',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Avocado',
    productNameEn: 'Avocado',
    price: 0.99,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '2',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Avocado',
    productNameEn: 'Avocado',
    price: 1.09,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '3',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Avocado',
    productNameEn: 'Avocado',
    price: 1.29,
    originalPrice: 1.49,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '4',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Avocado',
    productNameEn: 'Avocado',
    price: 1.19,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Hähnchenbrust (Chicken Breast)
  {
    id: '5',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Hähnchenbrust Filet',
    productNameEn: 'Chicken Breast',
    price: 5.99,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '6',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Hähnchenbrust',
    productNameEn: 'Chicken Breast',
    price: 5.49,
    originalPrice: 6.49,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '7',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Hähnchenbrust',
    productNameEn: 'Chicken Breast',
    price: 6.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '8',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Hähnchenbrust',
    productNameEn: 'Chicken Breast',
    price: 5.79,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Butter
  {
    id: '9',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Deutsche Markenbutter',
    productNameEn: 'Butter',
    price: 1.79,
    originalPrice: 2.29,
    unit: '250g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '10',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Butter',
    productNameEn: 'Butter',
    price: 1.89,
    originalPrice: null,
    unit: '250g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '11',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Butter',
    productNameEn: 'Butter',
    price: 2.49,
    originalPrice: null,
    unit: '250g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '12',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Butter',
    productNameEn: 'Butter',
    price: 1.99,
    originalPrice: null,
    unit: '250g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },
  {
    id: '13',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Butter',
    productNameEn: 'Butter',
    price: 1.99,
    originalPrice: null,
    unit: '250g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Vollmilch (Milk)
  {
    id: '14',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Vollmilch 3,5%',
    productNameEn: 'Whole Milk',
    price: 0.99,
    originalPrice: null,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '15',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Vollmilch',
    productNameEn: 'Whole Milk',
    price: 1.09,
    originalPrice: null,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '16',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Vollmilch',
    productNameEn: 'Whole Milk',
    price: 1.39,
    originalPrice: null,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '17',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Vollmilch',
    productNameEn: 'Whole Milk',
    price: 1.19,
    originalPrice: null,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Eier (Eggs)
  {
    id: '18',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Frische Eier',
    productNameEn: 'Eggs',
    price: 1.69,
    originalPrice: null,
    unit: '10 Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '19',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Eier',
    productNameEn: 'Eggs',
    price: 1.79,
    originalPrice: null,
    unit: '10 Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '20',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Eier',
    productNameEn: 'Eggs',
    price: 2.49,
    originalPrice: null,
    unit: '10 Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '21',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Eier',
    productNameEn: 'Eggs',
    price: 1.99,
    originalPrice: 2.29,
    unit: '10 Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },
  {
    id: '22',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Eier',
    productNameEn: 'Eggs',
    price: 1.89,
    originalPrice: null,
    unit: '10 Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Bananen (Bananas)
  {
    id: '23',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Bananen',
    productNameEn: 'Bananas',
    price: 1.49,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '24',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Bananen',
    productNameEn: 'Bananas',
    price: 1.39,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '25',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Bananen',
    productNameEn: 'Bananas',
    price: 1.69,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },

  // Bio Lachs (Salmon)
  {
    id: '26',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Bio Lachs Filet',
    productNameEn: 'Organic Salmon',
    price: 8.99,
    originalPrice: 10.99,
    unit: '200g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '27',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Bio Lachs',
    productNameEn: 'Organic Salmon',
    price: 9.49,
    originalPrice: null,
    unit: '200g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '28',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Bio Lachs',
    productNameEn: 'Organic Salmon',
    price: 11.99,
    originalPrice: null,
    unit: '200g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },

  // Olivenöl (Olive Oil)
  {
    id: '29',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Natives Olivenöl Extra',
    productNameEn: 'Extra Virgin Olive Oil',
    price: 4.99,
    originalPrice: null,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '30',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Olivenöl Extra Vergine',
    productNameEn: 'Extra Virgin Olive Oil',
    price: 4.79,
    originalPrice: null,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '31',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Olivenöl',
    productNameEn: 'Olive Oil',
    price: 5.99,
    originalPrice: null,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '32',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Olivenöl',
    productNameEn: 'Olive Oil',
    price: 5.49,
    originalPrice: 6.49,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Nudeln (Pasta)
  {
    id: '33',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Spaghetti',
    productNameEn: 'Pasta',
    price: 0.79,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '34',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Nudeln',
    productNameEn: 'Pasta',
    price: 0.69,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '35',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Nudeln',
    productNameEn: 'Pasta',
    price: 0.99,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '36',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Nudeln',
    productNameEn: 'Pasta',
    price: 0.89,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Reis (Rice)
  {
    id: '37',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Langkorn Reis',
    productNameEn: 'Long Grain Rice',
    price: 1.99,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '38',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Reis',
    productNameEn: 'Rice',
    price: 1.89,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '39',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Reis',
    productNameEn: 'Rice',
    price: 2.49,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '40',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Reis',
    productNameEn: 'Rice',
    price: 2.19,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Tomaten (Tomatoes)
  {
    id: '41',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Tomaten',
    productNameEn: 'Tomatoes',
    price: 2.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '42',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Tomaten',
    productNameEn: 'Tomatoes',
    price: 2.29,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '43',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Tomaten',
    productNameEn: 'Tomatoes',
    price: 2.99,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },

  // Gurke (Cucumber)
  {
    id: '44',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Salatgurke',
    productNameEn: 'Cucumber',
    price: 0.69,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '45',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Gurke',
    productNameEn: 'Cucumber',
    price: 0.59,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '46',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Gurke',
    productNameEn: 'Cucumber',
    price: 0.79,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },

  // Paprika (Bell Pepper)
  {
    id: '47',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Paprika',
    productNameEn: 'Bell Pepper',
    price: 1.99,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '48',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Paprika',
    productNameEn: 'Bell Pepper',
    price: 1.79,
    originalPrice: 2.29,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '49',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Paprika',
    productNameEn: 'Bell Pepper',
    price: 2.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '50',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Paprika',
    productNameEn: 'Bell Pepper',
    price: 2.19,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Kartoffeln (Potatoes)
  {
    id: '51',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Kartoffeln',
    productNameEn: 'Potatoes',
    price: 1.99,
    originalPrice: null,
    unit: '2kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '52',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Kartoffeln',
    productNameEn: 'Potatoes',
    price: 1.79,
    originalPrice: null,
    unit: '2kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '53',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Kartoffeln',
    productNameEn: 'Potatoes',
    price: 2.49,
    originalPrice: null,
    unit: '2kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '54',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Kartoffeln',
    productNameEn: 'Potatoes',
    price: 1.89,
    originalPrice: null,
    unit: '2kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Joghurt (Yogurt)
  {
    id: '55',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Naturjoghurt',
    productNameEn: 'Natural Yogurt',
    price: 0.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '56',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Joghurt',
    productNameEn: 'Yogurt',
    price: 0.45,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '57',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Joghurt',
    productNameEn: 'Yogurt',
    price: 0.69,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },

  // Käse (Cheese)
  {
    id: '58',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Gouda Käse',
    productNameEn: 'Gouda Cheese',
    price: 1.99,
    originalPrice: null,
    unit: '200g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '59',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Käse',
    productNameEn: 'Cheese',
    price: 1.79,
    originalPrice: 2.19,
    unit: '200g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '60',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Käse',
    productNameEn: 'Cheese',
    price: 2.49,
    originalPrice: null,
    unit: '200g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '61',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Käse',
    productNameEn: 'Cheese',
    price: 2.19,
    originalPrice: null,
    unit: '200g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Brot (Bread)
  {
    id: '62',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Vollkornbrot',
    productNameEn: 'Whole Grain Bread',
    price: 1.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '63',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Brot',
    productNameEn: 'Bread',
    price: 1.29,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '64',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Brot',
    productNameEn: 'Bread',
    price: 1.79,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },

  // Hackfleisch (Ground Beef)
  {
    id: '65',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Rinderhackfleisch',
    productNameEn: 'Ground Beef',
    price: 4.99,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '66',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Hackfleisch',
    productNameEn: 'Ground Beef',
    price: 4.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '67',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Hackfleisch',
    productNameEn: 'Ground Beef',
    price: 5.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '68',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Hackfleisch',
    productNameEn: 'Ground Beef',
    price: 4.79,
    originalPrice: 5.29,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Zwiebeln (Onions)
  {
    id: '69',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Zwiebeln',
    productNameEn: 'Onions',
    price: 1.49,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '70',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Zwiebeln',
    productNameEn: 'Onions',
    price: 1.29,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '71',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Zwiebeln',
    productNameEn: 'Onions',
    price: 1.69,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },

  // Äpfel (Apples)
  {
    id: '72',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Äpfel',
    productNameEn: 'Apples',
    price: 2.49,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '73',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Äpfel',
    productNameEn: 'Apples',
    price: 2.29,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '74',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Äpfel',
    productNameEn: 'Apples',
    price: 2.99,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '75',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Äpfel',
    productNameEn: 'Apples',
    price: 2.59,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Toastbrot (Toast Bread)
  {
    id: '76',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Toastbrot',
    productNameEn: 'Toast Bread',
    price: 1.09,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '77',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Toastbrot',
    productNameEn: 'Toast Bread',
    price: 1.19,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '78',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Toastbrot',
    productNameEn: 'Toast Bread',
    price: 1.69,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '79',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Toastbrot',
    productNameEn: 'Toast Bread',
    price: 1.29,
    originalPrice: 1.49,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },
  {
    id: '80',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Toastbrot',
    productNameEn: 'Toast Bread',
    price: 1.19,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Mineralwasser (Mineral Water)
  {
    id: '81',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Mineralwasser',
    productNameEn: 'Mineral Water',
    price: 0.19,
    originalPrice: null,
    unit: '1.5L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '82',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Mineralwasser',
    productNameEn: 'Mineral Water',
    price: 0.19,
    originalPrice: null,
    unit: '1.5L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '83',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Mineralwasser',
    productNameEn: 'Mineral Water',
    price: 0.49,
    originalPrice: null,
    unit: '1.5L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '84',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Mineralwasser',
    productNameEn: 'Mineral Water',
    price: 0.29,
    originalPrice: null,
    unit: '1.5L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },
  {
    id: '85',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Mineralwasser',
    productNameEn: 'Mineral Water',
    price: 0.29,
    originalPrice: null,
    unit: '1.5L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Kaffee (Coffee)
  {
    id: '86',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Kaffee',
    productNameEn: 'Coffee',
    price: 3.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '87',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Kaffee',
    productNameEn: 'Coffee',
    price: 3.99,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '88',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Kaffee',
    productNameEn: 'Coffee',
    price: 5.99,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '89',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Kaffee',
    productNameEn: 'Coffee',
    price: 4.49,
    originalPrice: 5.49,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },
  {
    id: '90',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Kaffee',
    productNameEn: 'Coffee',
    price: 4.29,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Zucker (Sugar)
  {
    id: '91',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Zucker',
    productNameEn: 'Sugar',
    price: 0.99,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '92',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Zucker',
    productNameEn: 'Sugar',
    price: 1.09,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '93',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Zucker',
    productNameEn: 'Sugar',
    price: 1.49,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '94',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Zucker',
    productNameEn: 'Sugar',
    price: 1.19,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Mehl (Flour)
  {
    id: '95',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Weizenmehl Type 405',
    productNameEn: 'Flour',
    price: 0.59,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '96',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Mehl',
    productNameEn: 'Flour',
    price: 0.69,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '97',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Mehl',
    productNameEn: 'Flour',
    price: 0.99,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '98',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Mehl',
    productNameEn: 'Flour',
    price: 0.79,
    originalPrice: 0.89,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Schlagsahne (Cream)
  {
    id: '99',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Schlagsahne',
    productNameEn: 'Cream',
    price: 0.59,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '100',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Schlagsahne',
    productNameEn: 'Cream',
    price: 0.69,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '101',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Schlagsahne',
    productNameEn: 'Cream',
    price: 0.99,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '102',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Schlagsahne',
    productNameEn: 'Cream',
    price: 0.79,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Thunfisch Dose (Canned Tuna)
  {
    id: '103',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Thunfisch Dose',
    productNameEn: 'Canned Tuna',
    price: 1.29,
    originalPrice: null,
    unit: '150g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '104',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Thunfisch',
    productNameEn: 'Canned Tuna',
    price: 1.49,
    originalPrice: null,
    unit: '150g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '105',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Thunfisch',
    productNameEn: 'Canned Tuna',
    price: 2.19,
    originalPrice: null,
    unit: '150g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '106',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Thunfisch',
    productNameEn: 'Canned Tuna',
    price: 1.69,
    originalPrice: 1.99,
    unit: '150g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },
  {
    id: '107',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Thunfisch',
    productNameEn: 'Canned Tuna',
    price: 1.59,
    originalPrice: null,
    unit: '150g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Tiefkühlpizza (Frozen Pizza)
  {
    id: '108',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Tiefkühlpizza Salami',
    productNameEn: 'Frozen Pizza',
    price: 1.99,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '109',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Pizza',
    productNameEn: 'Frozen Pizza',
    price: 2.19,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '110',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Pizza',
    productNameEn: 'Frozen Pizza',
    price: 3.49,
    originalPrice: null,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '111',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Pizza',
    productNameEn: 'Frozen Pizza',
    price: 2.49,
    originalPrice: 2.99,
    unit: 'Stück',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Waschmittel (Detergent)
  {
    id: '112',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Waschmittel flüssig',
    productNameEn: 'Detergent',
    price: 2.99,
    originalPrice: null,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '113',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Waschmittel',
    productNameEn: 'Detergent',
    price: 3.29,
    originalPrice: null,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '114',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Waschmittel',
    productNameEn: 'Detergent',
    price: 5.49,
    originalPrice: null,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '115',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Waschmittel',
    productNameEn: 'Detergent',
    price: 3.99,
    originalPrice: 4.49,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },
  {
    id: '116',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Waschmittel',
    productNameEn: 'Detergent',
    price: 3.49,
    originalPrice: null,
    unit: '1L',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Toilettenpapier (Toilet Paper)
  {
    id: '117',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Toilettenpapier',
    productNameEn: 'Toilet Paper',
    price: 2.99,
    originalPrice: null,
    unit: '10 Rollen',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '118',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Toilettenpapier',
    productNameEn: 'Toilet Paper',
    price: 3.19,
    originalPrice: null,
    unit: '10 Rollen',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '119',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Toilettenpapier',
    productNameEn: 'Toilet Paper',
    price: 4.49,
    originalPrice: null,
    unit: '10 Rollen',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '120',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Toilettenpapier',
    productNameEn: 'Toilet Paper',
    price: 3.49,
    originalPrice: 3.99,
    unit: '10 Rollen',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Zahnpasta (Toothpaste)
  {
    id: '121',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Zahnpasta',
    productNameEn: 'Toothpaste',
    price: 0.65,
    originalPrice: null,
    unit: '75ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '122',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Zahnpasta',
    productNameEn: 'Toothpaste',
    price: 0.79,
    originalPrice: null,
    unit: '75ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '123',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Zahnpasta',
    productNameEn: 'Toothpaste',
    price: 1.99,
    originalPrice: null,
    unit: '75ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '124',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Zahnpasta',
    productNameEn: 'Toothpaste',
    price: 0.99,
    originalPrice: null,
    unit: '75ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },
  {
    id: '125',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Zahnpasta',
    productNameEn: 'Toothpaste',
    price: 0.89,
    originalPrice: null,
    unit: '75ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Basmati Reis (Basmati Rice)
  {
    id: '126',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Basmati Reis',
    productNameEn: 'Basmati Rice',
    price: 2.49,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '127',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Basmati Reis',
    productNameEn: 'Basmati Rice',
    price: 2.79,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '128',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Basmati Reis',
    productNameEn: 'Basmati Rice',
    price: 3.99,
    originalPrice: null,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '129',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Basmati Reis',
    productNameEn: 'Basmati Rice',
    price: 3.29,
    originalPrice: 3.79,
    unit: '1kg',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Kichererbsen (Chickpeas)
  {
    id: '130',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Kichererbsen',
    productNameEn: 'Chickpeas',
    price: 0.79,
    originalPrice: null,
    unit: '400g Dose',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '131',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Kichererbsen',
    productNameEn: 'Chickpeas',
    price: 0.89,
    originalPrice: null,
    unit: '400g Dose',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '132',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Kichererbsen',
    productNameEn: 'Chickpeas',
    price: 1.49,
    originalPrice: null,
    unit: '400g Dose',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '133',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Kichererbsen',
    productNameEn: 'Chickpeas',
    price: 0.99,
    originalPrice: 1.19,
    unit: '400g Dose',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },
  {
    id: '134',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Kichererbsen',
    productNameEn: 'Chickpeas',
    price: 0.95,
    originalPrice: null,
    unit: '400g Dose',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Kokosmilch (Coconut Milk)
  {
    id: '135',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Kokosmilch',
    productNameEn: 'Coconut Milk',
    price: 1.09,
    originalPrice: null,
    unit: '400ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '136',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Kokosmilch',
    productNameEn: 'Coconut Milk',
    price: 1.19,
    originalPrice: null,
    unit: '400ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '137',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Kokosmilch',
    productNameEn: 'Coconut Milk',
    price: 1.99,
    originalPrice: null,
    unit: '400ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '138',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Kokosmilch',
    productNameEn: 'Coconut Milk',
    price: 1.49,
    originalPrice: null,
    unit: '400ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Linsen (Lentils)
  {
    id: '139',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Rote Linsen',
    productNameEn: 'Lentils',
    price: 0.99,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '140',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Linsen',
    productNameEn: 'Lentils',
    price: 1.09,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '141',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Linsen',
    productNameEn: 'Lentils',
    price: 1.79,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '142',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Linsen',
    productNameEn: 'Lentils',
    price: 1.19,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Mozzarella
  {
    id: '143',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Mozzarella',
    productNameEn: 'Mozzarella',
    price: 0.69,
    originalPrice: null,
    unit: '125g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '144',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Mozzarella',
    productNameEn: 'Mozzarella',
    price: 0.79,
    originalPrice: null,
    unit: '125g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '145',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Mozzarella',
    productNameEn: 'Mozzarella',
    price: 1.49,
    originalPrice: null,
    unit: '125g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '146',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Mozzarella',
    productNameEn: 'Mozzarella',
    price: 0.99,
    originalPrice: 1.19,
    unit: '125g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },
  {
    id: '147',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Mozzarella',
    productNameEn: 'Mozzarella',
    price: 0.89,
    originalPrice: null,
    unit: '125g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Nutella
  {
    id: '148',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Nutella',
    productNameEn: 'Nutella',
    price: 2.99,
    originalPrice: null,
    unit: '450g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '149',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Nutella',
    productNameEn: 'Nutella',
    price: 3.19,
    originalPrice: null,
    unit: '450g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '150',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Nutella',
    productNameEn: 'Nutella',
    price: 3.79,
    originalPrice: null,
    unit: '450g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '151',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Nutella',
    productNameEn: 'Nutella',
    price: 3.29,
    originalPrice: 3.69,
    unit: '450g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },

  // Haferflocken (Oats)
  {
    id: '152',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Haferflocken',
    productNameEn: 'Oats',
    price: 0.49,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '153',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Haferflocken',
    productNameEn: 'Oats',
    price: 0.59,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '154',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Haferflocken',
    productNameEn: 'Oats',
    price: 1.19,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '155',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Haferflocken',
    productNameEn: 'Oats',
    price: 0.69,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },
  {
    id: '156',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Haferflocken',
    productNameEn: 'Oats',
    price: 0.65,
    originalPrice: null,
    unit: '500g',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },

  // Ketchup
  {
    id: '157',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Tomaten Ketchup',
    productNameEn: 'Ketchup',
    price: 1.29,
    originalPrice: null,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '158',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Ketchup',
    productNameEn: 'Ketchup',
    price: 1.39,
    originalPrice: null,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '159',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Ketchup',
    productNameEn: 'Ketchup',
    price: 2.19,
    originalPrice: null,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '160',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Ketchup',
    productNameEn: 'Ketchup',
    price: 1.69,
    originalPrice: 1.99,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },
  {
    id: '161',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Ketchup',
    productNameEn: 'Ketchup',
    price: 1.49,
    originalPrice: null,
    unit: '500ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },

  // Senf (Mustard)
  {
    id: '162',
    storeId: '1',
    storeName: 'Lidl',
    storeBrandColor: '#0050AA',
    productName: 'Senf mittelscharf',
    productNameEn: 'Mustard',
    price: 0.49,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.lidl.de',
  },
  {
    id: '163',
    storeId: '2',
    storeName: 'Aldi Süd',
    storeBrandColor: '#00005F',
    productName: 'Senf',
    productNameEn: 'Mustard',
    price: 0.59,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.aldi-sued.de',
  },
  {
    id: '164',
    storeId: '6',
    storeName: 'Rewe',
    storeBrandColor: '#CC071E',
    productName: 'Senf',
    productNameEn: 'Mustard',
    price: 1.29,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.rewe.de',
  },
  {
    id: '165',
    storeId: '3',
    storeName: 'Penny',
    storeBrandColor: '#CD1719',
    productName: 'Senf',
    productNameEn: 'Mustard',
    price: 0.69,
    originalPrice: 0.89,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.penny.de',
  },
  {
    id: '166',
    storeId: '5',
    storeName: 'Netto',
    storeBrandColor: '#FFE600',
    productName: 'Senf',
    productNameEn: 'Mustard',
    price: 0.65,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.netto-online.de',
  },
  {
    id: '167',
    storeId: '4',
    storeName: 'Kaufland',
    storeBrandColor: '#E10915',
    productName: 'Senf',
    productNameEn: 'Mustard',
    price: 0.79,
    originalPrice: null,
    unit: '200ml',
    validFrom: '2026-03-17',
    validTo: '2026-03-23',
    sourceUrl: 'https://www.kaufland.de',
  },
];
